### ISSUE TITLE
General organisation/cleanups

### ISSUE THREAD

**Issue by linuxdaemon** [edwardslabs/CloudBot#152]
TODO
- [x] Load all plugins in plugins/ including subdirectories ( #190 )
- [ ] ~Move modules in cloudbot/util to plugins/util to allow util modules to be reloaded during runtime~
- [ ] Abstract some of the hook logic out of the core to allow easier runtime updates
- [ ] implement an alembic migration environment to allow easier updates of database tables for plugins ( #153 )
- [x] Move more of the hardcoded data out to data files ( #163 )
  - [x] Cheers in `badwords.py`
  - [x] `fight.py`
  - [x] `foaas.py`
  - [x] `halal.py`
  - [x] `highfive.py`
  - [x] `lenny.py`
  - [x] `lurve.py`
- [ ] Make sure the hook functions marked as coroutines actually need it, as they may be able to run in a different thread instead
- [x] Collapse similar plugins together
  - `attacks.py` ( #203 )
    - [x] `clinton.py`
    - [x] `trump.py`
    - [x] `glomp` and `bite` from `hookup.py`
    - [x] `spank` and `bdsm` from `spank.py`
    - [x] `lurve.py`
  - `foods.py`
    - [x] `halal.py` ( #204 )
- [x] Remove direct reference between `herald.py` and `grab.py` to allow them to be reloaded properly during runtime ( #190 )
- [ ] Add `connection` column to various DB tables ( Requires #153 )
  - [ ] `badwords`
  - [ ] `factoids`
  - [ ] `grab`
  - [ ] `herald`
  - [ ] `horoscope`
  - [ ] `karma`
  - [ ] `lastfm`
  - [ ] `librefm`
  - [ ] `profile`
  - [ ] `quote`
  - [ ] `seen_user`
  - [ ] `weather`
- [x] Clean up duplicate code in plugins
  - [x] `sportscores.py` ( #202 )

Any ideas / requests are welcome as comments on this issue or contact me via IRC as `linuxdaemon` in `#gonzobot` on [Snoonet](irc://irc.snoonet.org/gonzobot)
